project:
  type: website

website:
  title: "scUnify"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd
      - href: reference.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



